apiVersion: v1
kind: Service
metadata:
    name: service-deposito-konven
    labels:
        app: service-deposito-konven
        tier: backend
spec:
    selector:
        app: service-deposito-konven
        tier: backend
    ports:
        - port: 8084
          protocol: TCP
          targetPort: 8084
    type: ClusterIP
