apiVersion: apps/v1
kind: Deployment
metadata:
    name: middleware-jsonbe
spec:
    template:
        spec:
            containers:
                - name: middleware-jsonbe
                  image: ${PRIVATE_REGISTRY_PULL}/${CI_REGISTRY_NAMESPACE}/${CI_REGISTRY_IMAGE}:${CI_IMAGE_VERSION}
                  imagePullPolicy: Always
            restartPolicy: Always
            imagePullSecrets:
                - name: ${DOCKER_REGCRED}
    selector:
        matchLabels:
            app: middleware-jsonbe
