apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - ../../base

patches:
    - target:
          name: service-saving-konven
          kind: Deployment
      path: deployment.yaml

commonAnnotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

commonLabels:
    project: digibank

namespace: $KUBE_NAMESPACE
