apiVersion: v1
kind: Service
metadata:
    name: frontend-admin
    labels:
        app: frontend-admin
        tier: frontend
spec:
    selector:
        app: frontend-admin
        tier: frontend
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
          nodePort: 32050
    type: NodePort
