apiVersion: v1
kind: Service
metadata:
    name: service-deposito-syariah
    labels:
        app: service-deposito-syariah
        tier: backend
spec:
    selector:
        app: service-deposito-syariah
        tier: backend
    ports:
        - port: 8085
          protocol: TCP
          targetPort: 8085
    type: ClusterIP
