apiVersion: v1
kind: Service
metadata:
    name: service-deposito-syariah
    labels:
        app: service-deposito-syariah
        tier: backend
spec:
    selector:
        app: service-deposito-syariah
        tier: backend
    ports:
        - port: 8083
          protocol: TCP
          targetPort: 8083
          nodePort: 32008
    type: NodePort
