apiVersion: v1
kind: Service
metadata:
    name: service-cif
    labels:
        app: service-cif
        tier: backend
spec:
    selector:
        app: service-cif
        tier: backend
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    type: ClusterIP
