apiVersion: v1
kind: Service
metadata:
    name: olibsmiddleware-svc
    labels:
        app: olibsmiddleware
        tier: backend
spec:
    selector:
        app: olibsmiddleware
        tier: backend
    ports:
        - port: 1167
          protocol: TCP
          targetPort: 1167
    type: ClusterIP
