apiVersion: v1
kind: Service
metadata:
    name: service-user
    labels:
        app: service-user
        tier: backend
spec:
    selector:
        app: service-user
        tier: backend
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
          nodePort: 32008
    type: NodePort
