apiVersion: v1
kind: Service
metadata:
    name: service-transaction
    labels:
        app: service-transaction
        tier: backend
spec:
    selector:
        app: service-transaction
        tier: backend
    ports:
        - port: 8086
          protocol: TCP
          targetPort: 8086
    type: ClusterIP
