apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-user
spec:
    template:
        spec:
            containers:
                - name: service-user
                  image: ${PRIVATE_REGISTRY_PULL}/${CI_REGISTRY_NAMESPACE}/${CI_REGISTRY_IMAGE}:${CI_IMAGE_VERSION}
                  imagePullPolicy: Always
            restartPolicy: Always
            imagePullSecrets:
                - name: ${DOCKER_REGCRED}
    selector:
        matchLabels:
            app: service-user
